### PR TITLE
CAF-3708: Updated to log to the standard output streams

### PR DESCRIPTION
**Pull request by dermot-hardy**
https://jira.autonomy.com/browse/CAF-3708

A developer build for this has been created:
http://sou-jenkins2.hpeswlab.net/job/CAFapi/view/Developer/job/CAFapi~opensuse-tomcat-image~logging~CI/

It can be tested using this image:

    docker image pull cafinternal/prereleases:opensuse-tomcat-1.1.0-logging-SNAPSHOT

### CODE REVIEW

**Comment by rob-duewer** [comment]
So the logging addition looks fine.  I'm good with that.

But I have some questions about the dockerfile before you made these additions.
1) Why are you pulling a latest opensuse image to use for these tasks and not using the cafapi/opensuse-jre8:1.0 for that process?  (I believe you can use it as both a main from and as a builder.  Adding tar to our cafapi/opensuse-jre8 wouldn't be a terrible idea, since it's so small. But since we need xslt too, those on the one run line for full build seem smarter to me.)
2) It looks like you are trying to retrieve the fixed version of TC from a fixed public mirror.  Shouldn't this be changed to a web target we control? Or copied from next to the dockerfile? Or come up with a way to get the current mirror list from their CGI (which I believe serves a random or unloaded mirror) and then retrieve from that target?  (Just wget  and then read for the ..."<p>You are currently using <b>"... should work?)  Everything from there is then built from that path.  That's something we can put in a script to keep the layers still thin.
3) Why are we using a builder image at all?  All we're doing is unpacking TC and modifying the server.xml with the transform?  You can do all that in the actual image definition on the one RUN line, no?  (The builder would be more useful if it was more complex.  But since the image right now this is still coming out as 6 layers anyhow because of the copy from builder + run line.  But because you can have multiple copy commands on one line; it should all be doable on the live image only.  No?

**Comment by rob-duewer** [comment]
Ignore that strange bolding in the above comment... :)

**Comment by dermot-hardy** [comment]
1. Just because we don't need Java.  I wouldn't be terribly against using the `opensuse-jre8` image but it's not particularly important since the image is getting thrown away anyway as soon as the build tasks are complete.
2. That was just the url that @bhagyashreen had in the original Dockerfile where she downloaded it from (see https://github.com/CAFapi/opensuse-tomcat-image/blob/v1.0.0/src/main/docker/Dockerfile#L19).  If you think it's not a stable url then yes we should change it.  Or we could go back to having the tarball checked in alongside the Dockerfile, although I don't really like the way that bloats the repository.  I'm also happy to do something more complex like you suggest but it would have to be another JIRA.
3. Because we have to introduce tools that you may not want in the real image.  And also it keeps the size of the image down.  For example, by deleting the "manager" web app in a builder image it is not in any of the layers of the final image, which keeps it as trim as possible.

**Comment by rob-duewer** [comment]
1) I would switch to our base, even with it being thrown away.  Or at a minimum, use the fixed public opensuse tag (:42.3) instead of latest.  Not that it's likely to break, but depending on how long it hangs around, I think that would be smarter.
2) Check out how apache is using a cgi to pick a mirror.  @bhagyashreen just used the one she happened to be served at that time.  But they make no bones that the mirror list is fluid and will change without notice.  So yes, I would put the fixed tar here for the short term.  (9mb won't kill us)  And take a ticket to get smarter about pulling it for the future.  (Then we can dump the tar out of our project.)
3) That is true about saving the bytes for the removal of the tc apps, so I'm with it then.  (I'm less worried about adding tar and xslt to the final image though...) Especially if the build from dockerfile isn't too long with the extra temp image construction and is being cleaned up properly; then that's fine with me.

Thanks!

**Comment by dermot-hardy** [comment]
1. I've raised https://github.com/CAFapi/opensuse-tomcat-image/pull/2 for this.
2. I've raised https://github.com/CAFapi/opensuse-tomcat-image/pull/3 to fix this immediately.  @bhagyashreen Could you raise a JIRA on your board to re-introduce downloading in the safe way that @rob-duewer has discussed?
3. Of course it's true.  I never tell you lies.  Sometimes it just seems to take you a while to realize that.

**Pull request merged**
