### PR TITLE
Add health-check capability

### PR DESCRIPTION
**Pull request by dermot-hardy**

### CODE REVIEW

**Comment by rob-duewer** [comment]
Looks fine to me.  But before it goes in, are all the tomcat operating applications ready for this?  (IE have they already agreed and started putting at least some war into $CATALINA_HOME/adminapps/ROOT/ ?  I just figured that all the tomcat consuming containers we have can do this first before this checkin is promoted, as I don't think the old TC images they were using would pay any attention to an extra file shoved into that directory.  Right?

**Comment by dermot-hardy** [comment]
They're currently using the [v1.0](https://github.com/CAFapi/opensuse-tomcat-image/releases/tag/v1.0.1) image so they don't need to be updated until they are moved on to using this v1.1 version.  Thinking about it, we should probably make this v2.0 since it does impose an extra requirement that wasn't there before.

**Comment by rob-duewer** [comment]
I'm not at all sure everyone is using 1.0.  Just from the audit of 1.6.3; there were at least 3 being used.

I'll send you that list privately in a few.

**Review by jason-labriola — APPROVED** [review]
Everything in Verity org was moved over to use 1.0

**Pull request merged**
